version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.maven:maven-compat
    versions:
    - 3.8.1
  - dependency-name: org.apache.maven:maven-plugin-api
    versions:
    - 3.8.1
  - dependency-name: org.apache.maven:maven-model
    versions:
    - 3.8.1
  - dependency-name: org.apache.maven:maven-core
    versions:
    - 3.8.1
  - dependency-name: org.apache.maven:maven-artifact
    versions:
    - 3.8.1
  - dependency-name: com.puppycrawl.tools:checkstyle
    versions:
    - "8.40"
    - "8.41"
    - 8.41.1
  - dependency-name: org.codehaus.mojo:animal-sniffer-maven-plugin
    versions:
    - "1.20"
